### PR TITLE
Improve seo - issue #75

### PR DESCRIPTION
**Pull request by psantos10**
More tags can be added.

### CODE REVIEW

**Comment by pragmaticivan** [comment]
@psantos10 thanks! For this one you should create a branch "from master" not use the last one you created for the last Pull Request.

**Comment by pragmaticivan** [comment]
I would recommend you to create a branch from master and do a new Pull Request for this one.

**Comment by psantos10** [comment]
You are right @pragmaticivan 

I make a mistake at the begging with the first PR. I didn't expect to make another PR before the first was accepted.

**Comment by psantos10** [comment]
@pragmaticivan there is a way to accept this PR #128 first? 

at least  I will not have to restart the translation work.

**Comment by pragmaticivan** [comment]
I'm reviewing now. You should cancel this PR any way, because you're going to squash your commits in master when I review everything.

**Comment by doomspork** [comment]
Thanks for starting on the SEO stuff @psantos10, I appreciate the help!

**Comment by psantos10** [comment]
Closing this PR. A new one will be sent as soon as possible

**Pull request closed without merging**
