### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by brain-geek**
I've started translating the project to russian. Here is the first lesson.

### CODE REVIEW

**Comment by pjhampton** [comment]
Awesome! Thanks @brain-geek :+1: 

It may be helpful to create an issue like #89 so we can all follow the progress. There is a lot of translations happening simultaneously.

**Comment by brain-geek** [comment]
@pjhampton Thanks for idea! 

I'll create one.

**Comment by pjhampton** [comment]
Maybe @joneslee85 this approach might be useful for the Vietnamese lessons as well? It might be useful to establish this protocol across all languages. What you think?

**Comment by doomspork** [comment]
Take a peek at #71 if you guys don't mind, any suggestions on how to manage these different translations would be greatly appreciated!

**Pull request merged**
