### PR TITLE
Update composition.md

### PR DESCRIPTION
**Pull request by RTJ**
Translation updated

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://elixirschool.rtj-patch-4.doomspork-elixir-school-3c64f857cd94b93cd0cf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://elixirschool.rtj-patch-4.doomspork-elixir-school-3c64f857cd94b93cd0cf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by doomspork** [comment]
Thanks @RTJ!  

@erickgnavar or @jesusangelm could you review this please?  Thanks!

**Comment by jesusangelm** [comment]
Looks great for me! 
Thanks @RTJ!

**Comment by doomspork** [comment]
Thanks @jesusangelm :+1:

**Pull request merged**
