### PR TITLE
[BN] Translated the Control Structure lesson

### PR DESCRIPTION
**Pull request by code-shoily**
As discussed in the IM, I've translated the lesson on `Control Structure`. Thanks @masnun it was refreshing to take a stab at `with` statement again.

Please check the translation out. You too @prio101 

Thanks :)

### CODE REVIEW

**Comment by prio101** [comment]
looks good...

**Comment by doomspork** [comment]
Thank you for all of your hard work @code-shoily, @prio101, and @masnun!

**Comment by masnun** [comment]
Nice! 👍

**Comment by code-shoily** [comment]
@doomspork I guess we can merge this one too :)

**Comment by nscyclone** [comment]
Thanks, @code-shoily, @prio101 and @masnun!

**Pull request merged**
