### PR TITLE
Genstage Lesson Proposal on top of @doomspork's original

### PR DESCRIPTION
**Pull request by ybur-yug**
## See prior thread [here](https://github.com/doomspork/elixir-school/pull/759)

### CODE REVIEW

**Comment by doomspork** [comment]
Thanks @ybur-yug, I'm going to go through this now.

**Comment by doomspork** [comment]
@ybur-yug I think this is great but still think there's a lot we can take off that doesn't fit with our current lesson format (the whole Postgres portion for instance).  I've gone ahead and pulled your changes to begin editing them.  What I'd like to do is merge this, apply my changes, and push it up for a team wide review.  Thoughts?

**Comment by ybur-yug** [comment]
@doomspork that works for me. I'll keep the origin bit I built up as I have it now for my own stuff and might just make it a blog post and link to the lesson once its up or something. Its bigger in scope but I think it might have some use elsewhere. So have at it.

**Comment by doomspork** [comment]
Thanks @ybur-yug!  I think the additional sections you added would be great for a blog post as they're quite useful and informative.

**Pull request merged**
