### PR TITLE
Add Composition to Portuguese(Brazil)

### PR DESCRIPTION
**Pull request by pragmaticivan**
Related to #89

### CODE REVIEW

**Comment by doomspork** [comment]
@pragmaticivan you are a machine!  Thank you so much for your contributions.  

I'm going to give @tiagobarreto an opportunity to look at these before I merge.

**Comment by pragmaticivan** [comment]
Thanks :D :+1:

**Comment by pragmaticivan** [comment]
@tiagoamaro comment in the PR instead of my branch.

**Comment by tiagobarreto** [comment]
@pragmaticivan sorry! :+1:

**Pull request merged**
