### PR TITLE
Update pattern-matching.md

### PR DESCRIPTION
**Pull request by gemantzu**

### CODE REVIEW

**Comment by ybur-yug** [comment]
I forget if we had someone else to review changes in greek. If we do let me know @gemantzu otherwise I can merge this whenever you just give me a thumbs up :)

**Comment by gemantzu** [comment]
Unfortunately, right now there is no one that I know of.

**Comment by brain-geek** [comment]
@Kosmas , could you look through? (pinging you, as you've contributed #215 and few more for the Greek translation )

**Comment by Kosmas** [comment]
@brain-geek that looks good.
Not sure about the translation to 'throw an error' @gemantzu. Is that how is commonly used?

**Comment by gemantzu** [comment]
not sure myself @Kosmas , I know I use it like that in my daily usage, that's how I translated it here (and all the other occurrences of the phrase in elixir-school).

**Comment by Kosmas** [comment]
OK @gemantzu . If someone does not like it they can change it.
Good work!

@ybur-yug please merge.

**Comment by nscyclone** [comment]
Thanks, @gemantzu and @Kosmas!

**Pull request merged**
