### PR TITLE
Create a Toggle-able Dark Theme

### PR DESCRIPTION
**Pull request by jereinhardt**
Thought I'd try to take a swing at #1465.  This PR changes the color scheme to create a dark theme for the site.  It also adds a toggle button at the bottom of the sidebar that allows users to switch back and forth between dark and default themes.

### CODE REVIEW

**Comment by doomspork** [comment]
@jereinhardt this is awesome!  I'll take a peek this week.  I've asked @burden to also review this, he was working on a dark theme as well 👍

**Comment by burden** [comment]
@jereinhardt it appears great minds think alike :) I was also working on a theme as @doomspork mentioned.  It even looks like we started in the same place — same css, slightly different. Nevertheless, I wanted to share some thoughts and hoped we could discuss them. 

The first thing that jumped out to me is that it appears that the cookie's path is set to the page where the button was pressed.  We want the theme choice to be reflected throughout the visitor's experience on the site, but the current implementation is limited to per-page.  I don't believe this is by design, is it?
screen shot 2018-10-15 at 2 45 50 pm

The other thing I think we should address is whether we need an extra CSS file or not. Instead of making everyone download a slightly modified version of the original CSS, we should be adding onto `main.scss` to minimize the download, which is what I did over on my branch. Do you want to take a peek? https://github.com/elixirschool/elixirschool/pull/1555

I'm hoping we can figure out a way to incorporate our changes together. I spaced on jQuery's cookie implementation, which could be something for you to improve.

**Comment by doomspork** [comment]
@jereinhardt I'd hate for your work to not be included.  @burden is your branch complete?  Is there anything that's left that @jereinhardt could help with?

I hate when folks work doesn't get merged 🙁

**Comment by jereinhardt** [comment]
No worries.  Honestly, doing the work and then comparing it to @burden's helped me learn a few things, so it's not for nothing 😄

**Comment by doomspork** [comment]
@jereinhardt I hope we can find other opportunities for you to contribute!  I really do appreciate you taking the time to open this PR 😁

**Pull request closed without merging**
