### PR TITLE
Starting the french translation

### PR DESCRIPTION
**Pull request by tchoutri**
Here's the first french translation : front page and `basics` lesson.

### CODE REVIEW

**Comment by pjhampton** [comment]
References #196 

Thanks @tchoutri. You rock!

**Comment by tchoutri** [comment]
Yeah, not so fast, I managed to mess up with the branches. I'm re-cloning a fresh repo… :D

**Comment by julienXX** [comment]
@tchoutri do you need some help with the translations? I could translate some files if that's needed.

**Comment by pjhampton** [comment]
@julienXX Super thanks for offering your help!! Translations are on a lesson by lesson, first come first serve basis. See this: https://github.com/doomspork/elixir-school/issues/196

@tchoutri Should I close this PR then and merge the other?

**Comment by doomspork** [comment]
Closing per discussion above.  Thanks @tchoutri and @julienXX :grinning:

**Pull request closed without merging**
