### PR TITLE
Update testing.md

### PR DESCRIPTION
**Pull request by gemantzu**
The module is ExUnit.CaptureIO

### CODE REVIEW

**Comment by nscyclone** [comment]
Thanks, @gemantzu!
This is also [present](https://github.com/doomspork/elixir-school/search?utf8=%E2%9C%93&q=captureIO) in some other translations. Would you like take to take care of them?

**Comment by gemantzu** [comment]
Sure, I will do them now and report back.

**Comment by gemantzu** [comment]
Ready. Take a look it detects a change in PL translation in line 150, but I did not touch anything and I don't see a change there (maybe a Github bug?)

**Comment by doomspork** [comment]
Thank you @gemantzu!!

**Pull request merged**
