### PR TITLE
[JP] Translate GenStage and Protocols

### PR DESCRIPTION
**Pull request by rinosamakanata**
Hi, 
I translated GenStage and Protocols lessons into Japanese.
Please check it. Thank you :)

### CODE REVIEW

**Comment by doomspork** [comment]
Hi @rinosamakanata thank you very much for your contribution and welcome!  @3100 do you have time to look this over?

**Comment by 3100** [comment]
Hi, @rinosamakanata. Nice work! 
I suppose 'sink' can be translated to '受け手', but what do you think?

**Comment by rinosamakanata** [comment]
Hi, @3100. Thank you for review and comment!
Surely I agree. The word 'シンク' could be difficult to understand in this context.
So I translated 'sink' into '受け手' as you suggested, and correspondingly I changed 'ソース' to '送り元'. How does that look?

**Comment by 3100** [comment]
@rinosamakanata Thank you very much!

**Pull request merged**
