### PR TITLE
[JP] Update translation in 'basics/control-structures'

### PR DESCRIPTION
**Pull request by hinamiyagk**
Elixir 1.2 updates(`with` expression)

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @hinamiyagk!  @3100 can you take a look at this when you have some time?

**Comment by 3100** [comment]
Nice work. 
I suggest some points below, but  I will leave the choices up to you, @hinamiyagk .

- It would be better to translate the phrase `The special form` as `スペシャルフォーム` or `特殊形式` because it is a well-known technical term in some programming languages. 
- `知っておくだけで良いです` seems to be more natural translation of `only need to know`.

**Comment by hinamiyagk** [comment]
Updated

**Comment by 3100** [comment]
Thank you so much :+1:

**Comment by doomspork** [comment]
Thank you @hinamiyagk and @3100 👍

**Pull request merged**
