### PR TITLE
Update pattern-matching.md

### PR DESCRIPTION
**Pull request by RTJ**
Commented lines translated into Spanish

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://elixirschool.rtj-patch-3.doomspork-elixir-school-3c64f857cd94b93cd0cf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://elixirschool.rtj-patch-3.doomspork-elixir-school-3c64f857cd94b93cd0cf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by doomspork** [comment]
Thanks @RTJ!

@erickgnavar / @jesusangelm this one too if you have a moment, thank you

**Comment by doomspork** [comment]
@erickgnavar is this PR good to merge?

**Comment by erickgnavar** [comment]
Yep, sorry for the late response

**Comment by doomspork** [comment]
No worries, I appreciate all of your help!

**Comment by doomspork** [comment]
Thank you @RTJ!

**Pull request merged**
