### PR TITLE
Add the new section for libraries

### PR DESCRIPTION
**Pull request by nscyclone**
During discussion in #702 we came to a decision that we need a new separate section for libraries.
This PR adds the mentioned section and it also hides the sections without lessons from the sidebar.
cc @doomspork @brain-geek @ybur-yug @Koziolek and everyone else.

Once this will be merged, #702 and #431 will require corresponding updates (location, order and category). Then I'll also create an issue for translations.

### CODE REVIEW

**Comment by brain-geek** [comment]
Let's merge it with at least one lesson in this category. e.g. after #702 gets merged.

**Comment by Koziolek** [comment]
Looks nice, let't merge it with first lesson plus add some info about library vs specific, because sometimes is hard to say what is what.

**Comment by ybur-yug** [comment]
Looks like we need to update the configuration for the new ruby version on Heroku to get this one synced properly with master now

**Comment by nscyclone** [comment]
Thanks @ybur-yug!
Actually the conflict was caused by another set of changes. Anyway, I merged latest master into this branch and resolved it, so the latter one is mergeable again.

**Pull request merged**
