### PR TITLE
[JP] Improve translation in metaprogramming lesson

### PR DESCRIPTION
**Pull request by hinamiyagk**
* Fix wrong translation
* strip unnecessary comments
* Make some expressions more natural

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @hinamiyagk, @3100 could you please review this one too?

**Comment by 3100** [comment]
@hinamiyagk LGTM 👍

**Comment by doomspork** [comment]
@hinamiyagk could you rebase your branch?  It's currently not able to merge.

**Comment by hinamiyagk** [comment]
resolved.

**Comment by 3100** [comment]
@hinamiyagk Great work. Thank you!

**Comment by doomspork** [comment]
Thank you @hinamiyagk and @3100! 👍

**Pull request merged**
