### PR TITLE
add mobile styles to nav

### PR DESCRIPTION
**Pull request by jessejanderson**
image

### CODE REVIEW

**Comment by jessejanderson** [comment]
Not sure the best way to do this, but it would be great if the navigation was toggled close by default on mobile.

**Comment by doomspork** [comment]
I agree, the menu is getting a bit long these days.  Any suggestions?  One option might be to have all sections closed by default for everyone.

**Comment by doomspork** [comment]
Collapsing the menu may a good solution to #96

**Comment by doomspork** [comment]
@pjhampton and @pragmaticivan, what do you think about collapsing the menus by default?  Right now they're a bit long, this might serve to buy us some time building a whole new site.

Thoughts?

**Comment by pjhampton** [comment]
This looks swell. 

**All devices** - Maybe it could paginated? I say this because I think it maybe a good idea to show at least the basic lessons in the menu my default, until maybe they move to another section? 

**Only mobile** - If this just applies to mobile, then I think that is good :+1: 

thanks @jessejanderson

**Comment by pragmaticivan** [comment]
I like the new just mobile menu, just tested here locally, but would collapse the menu and just show the basics area. And also need to detect when an advanced area is active, so it needs to show the advanced area opened instead the basic area.

**Comment by doomspork** [comment]
Thanks for your thoughts @pragmaticivan and @pjhampton.  I'm going to merge this as-is but I'm open to a PR to improve collapsing the menus.

Thanks again @jessejanderson this is great :+1:

**Pull request merged**
