### PR TITLE
Use space around cons operator

### PR DESCRIPTION
**Pull request by eksperimental**
In the same vein as https://github.com/doomspork/elixir-school/pull/1076

### CODE REVIEW

**Comment by doomspork** [comment]
You're the 💣 @eksperimental, thanks again for all your help.

**Comment by eksperimental** [comment]
I thought you were going to say "the :hankey:".
:laughing:  :laughing:  :laughing:

**Comment by eksperimental** [comment]
@doomspork Do you think it would help to adhere to a style-guide?
There are a few around, I contribute myself to one, and pretty mucho adhere to another when I contribute to Elixir. I think it can bring consistency and clarity to the code.
If you are interested, I can study all of them around and see which one fits this project better.
WDYT?

**Comment by doomspork** [comment]
@eksperimental that would probably be a good idea.  We have a basic styleguide for lesson contributions but necessarily for example code: https://github.com/doomspork/elixir-school/wiki/Lesson-Styleguide

I tend to follow: https://github.com/christopheradams/elixir_style_guide at work 👍

**Pull request merged**
