### PR TITLE
Update functions.md

### PR DESCRIPTION
**Pull request by gemantzu**

### CODE REVIEW

**Comment by gemantzu** [comment]
I did a small review with a friend alongside me, we found some typos and some phrases that could be rewritten in a different way. @Kosmas can you take a look when you have the time?

**Comment by Kosmas** [comment]
@gemantzu well done!
:+1: 

Good to merge :-)

**Comment by doomspork** [comment]
This is fantastic @gemantzu, thank you to both you and @Kosmas!

**Comment by gemantzu** [comment]
Thnx @Kosmas for your review, and you @doomspork for those extremely helpful guides! They have been a blast so far!

**Pull request merged**
