### PR TITLE
Changing versions for libraries to versions that actually work

### PR DESCRIPTION
**Pull request by rodrigodealer**
I was following the lessons and had to change some versions, maybe this would be useful for people in the future. 

I changed the versions in the portuguese version as well.

### CODE REVIEW

**Comment by doomspork** [comment]
Howdy @rodrigodealer!  Welcome and thank you for your contribution.  Would you be willing to apply this change to all the other languages?

**Comment by rodrigodealer** [comment]
I'll do that! 👍 As soon as I have it changed, I'll tag you again.

**Comment by rodrigodealer** [comment]
@doomspork I have updated the branch, please take a look.

**Comment by doomspork** [comment]
Wonderful!  Thank you so much @rodrigodealer!! 😀

**Pull request merged**
