### PR TITLE
Teatro config

### PR DESCRIPTION
**Pull request by doomspork**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://elixirschool.teatro-config.doomspork-elixir-school-3c64f857cd94b93cd0cf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://elixirschool.teatro-config.doomspork-elixir-school-3c64f857cd94b93cd0cf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by pragmaticivan** [comment]
;/ I sent a message today about some questions they didn't answer yet.

**Comment by pragmaticivan** [comment]
We also need to handle the base url, so any change to make it work will not end up working any way without that.

**Comment by doomspork** [comment]
I know we'll need to configure the base url, one thing at a time.  For now I just want to get the site to deploy :grinning:

**Comment by doomspork** [comment]
I disabled Teatro until we can figure out the config, the PR comments and annoying since they don't work.

**Comment by doomspork** [comment]
Maybe we should investigate Heroku's pipeline and review apps?

**Comment by pragmaticivan** [comment]
Yes, would be better. This project had some success in a open source rails project worked with. Sad ;/ You can close this pr if you want.

**Pull request closed without merging**
