### PR TITLE
Explain syntax for updating maps and access atom keys. Fix #402

### LINKED ISSUE #402: Never mentioned how to update a map before demonstrating it on struct
In Basics -> Composition -> structs there is an explanation of how to update a struct:

> We can update our struct just like we would a map:

However, update a map was never introduce before.

### PR DESCRIPTION
**Pull request by Nagasaki45**
I took the text for the official [elixir getting-started guid](http://elixir-lang.org/getting-started/keywords-and-maps.html#maps), and simplified the example a bit.

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @Nagasaki45!  I think this is something we will want added to the translations as well.

**Comment by Nagasaki45** [comment]
@doomspork, how can I help with that?

**Comment by doomspork** [comment]
@Nagasaki45 I'm wondering that myself!  These little changes are a bit tougher to track and make sure they're translated.  Before I merge this I want to ping a few of the translators and get some thoughts on tracking these, sound good?

**Comment by Nagasaki45** [comment]
Sounds great!
@meyvain, my significant other, showed interest in helping to translate this to spanish.

**Comment by doomspork** [comment]
That would be fantastic @Nagasaki45 & @meyvain!

**Comment by doomspork** [comment]
Thank you @Nagasaki45 👍

**Pull request merged**
