### PR TITLE
[JP] Add error handling lesson

### PR DESCRIPTION
**Pull request by hinamiyagk**

### CODE REVIEW

**Comment by hinamiyagk** [comment]
Especially, I'm not sure about translation of this phrase:
`an important part of the fault tolerance of Elixir`

**Comment by doomspork** [comment]
Thank you @hinamiyagk!  @3100 could you look at this?  Thank you both 👍

**Comment by 3100** [comment]
@hinamiyagk Sorry for the delay. LGTM 👍

**Comment by hinamiyagk** [comment]
Should I resolve conflict?

**Comment by 3100** [comment]
@hinamiyagk I would appreciate your resolving it.

**Comment by hinamiyagk** [comment]
resolved.

**Comment by doomspork** [comment]
Thank you @hinamiyagk and @3100 👍

**Pull request merged**
