### PR TITLE
Updating/fixing grammatical errors at spanish translations

### PR DESCRIPTION
**Pull request by roadev**
Updating/fixing grammatical errors at spanish translations.

### CODE REVIEW

**Comment by doomspork** [comment]
Thanks for your help @roadev.  

Ping @jesusangelm, @erickgnavar, @milmazz for review :grinning:

**Comment by erickgnavar** [comment]
Looks good 😃
Thanks @roadev

**Comment by doomspork** [comment]
Thanks @erickgnavar

**Comment by roadev** [comment]
:)
You're welcome!

**Pull request merged**
