### PR TITLE
Vietnamese translation for Basics - Collections

### PR DESCRIPTION
**Pull request by vnnoder**
@joneslee85 Please help to review :smiley:

### CODE REVIEW

**Comment by doomspork** [comment]
You guys are awesome, thank you so much for your contributions!  

@joneslee85 & @vnnoder are you on Twitter?  When I announce the Vietnamese lessons I'd like credit you all.

**Comment by joneslee85** [comment]
@doomspork my nick handler is @joneslee85 on Twitter

**Comment by doomspork** [comment]
Thank you @joneslee85 :+1:

**Comment by vnnoder** [comment]
hi @doomspork, my handler is vuminhtan, thanks

**Pull request merged**
