### PR TITLE
[BN] Added translation for Mix Task

### PR DESCRIPTION
**Pull request by code-shoily**
@masnun @prio101 please take a look at this one. Thanks in advance.

### CODE REVIEW

**Comment by code-shoily** [comment]
@masnun @prio101 any thought on this? This one's the last of the `Basic` section to be merged.

**Comment by prio101** [comment]
it looks fine to me

**Comment by code-shoily** [comment]
@doomspork @nscyclone can you please merge this one? And the Bengali translation of the `Basic` section should end be completed now (Pass 1)

**Comment by nscyclone** [comment]
Thanks a lot for all of your great job, @code-shoily and @prio101!

**Pull request merged**
