### PR TITLE
[PL] Remove untranslated chapter

### PR DESCRIPTION
**Pull request by eksperimental**
- ~~gr/lessons/specifics/eex.md: is an empty file.~~
- pl/lessons/advanced/protocols.md: only the title has been translated.

### CODE REVIEW

**Comment by gemantzu** [comment]
Check out [this] (https://github.com/doomspork/elixir-school/commit/d55c1a19abd434cfd5680b76fe41563d547ca4bc) commit, it is the one emptying gr/lessons/specifics/eex.md (it's your commit, thats why I reference it)

**Comment by doomspork** [comment]
@gemantzu do we need to add back that lesson or is it okay being removed for now?

**Comment by gemantzu** [comment]
I think it should be added back, I can only assume it was only removed by mistake.

**Comment by doomspork** [comment]
You're correct @gemantzu, that is a translated lessons and not a placeholder!  @eksperimental can you take a look at fixing that?

**Comment by eksperimental** [comment]
I'm  still wondering how this file got emptied out. I will submit a commit reverting that change, and rebase this one.

**Comment by eksperimental** [comment]
I have submitted a new PR to fix the issue with the Greek translation (https://github.com/doomspork/elixir-school/pull/1124)
and I have updated this PR accordingly

**Comment by eksperimental** [comment]
BTW, thank you @gemantzu for finding out that mistake of mine

**Comment by doomspork** [comment]
Thank you @eksperimental 👍

**Pull request merged**
