### PR TITLE
[bn] Updated index and translated basics/basics.md

### PR DESCRIPTION
**Pull request by masnun**
These are for the Bangla language (`bn`).

- Updated the `index.md` 
- Copied the `en` lessons to `bn` to complete the structure
- Translated `basics/basics.md` to Bangla.

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @masnun!  @prio101 would you like to take a peek at this?  You're the only other translator in Bangla 😀

**Comment by mis-wtag** [comment]
Hey hi @doomspork.  And thanks to @masnun Brother.  @doomspork These changes looks great.. :)

**Comment by masnun** [comment]
Thanks for the review @mis-wtag . I guess we can merge this.

**Comment by code-shoily** [comment]
Mafinar here. 
@masnun @mis-wtag glad to see you guys coming up with the translation. Excellent translation @masnun 
@mis-wtag I would suggest we keep a few terms "as-is" such as "Fault Tolerant", "Functional Programming", "Scalable" etc as the Bengali translation of those would be unfamiliar even with the seasoned programmer. 
I have also started with the translation and will contribute by the weekend, could we collaborate on the chapters that we're taking up on? I guess that would complete it faster :)

Thanks guys!

**Comment by masnun** [comment]
Good to see you here @code-shoily - yes, before we start translating a chapter, let's inform others. How can we do that? May be create an issue here?

I have created a `#bangladesh` room in elixir slack. We can discuss there too!

**Comment by code-shoily** [comment]
@masnun awesome. See you you there.
And you're right about the inform part, I guess creating issues would be good. @uroybd (Utsob Roy) has also shown interest in participating, had a conversation with him this morning. His writing skill is superb.

**Comment by masnun** [comment]
OK, we can use issues, no problem.

**Comment by nscyclone** [comment]
Issues with task lists have worked well for tracking and organizing so far. Please take a look at #201 or #220.

**Comment by prio101** [comment]
By the way .... that @mis-wtag is me 😛  .... Thanks everyone ...

**Comment by doomspork** [comment]
It's great to see this discussion!  Thank you @masnun, @prio101, @mis-wtag, and @code-shoily!

@code-shoily per your comment above, should we make some changes to this translation before we merge or are you happy with it?

**Comment by code-shoily** [comment]
@doomspork the translation's great, please merge :+1:

**Comment by masnun** [comment]
Thanks.

**Comment by doomspork** [comment]
Thank you @masnun!!

**Pull request merged**
