### PR TITLE
Improvements in Collections

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by doomspork** [comment]
This is great, thank you @eksperimental!  Could you please change the `version` in the Jekyll meta data to `1.1.0`?

**Comment by eksperimental** [comment]
@doomspork done.
Could you please link me to a doc where it explains what is the protocol for updating the version number

**Comment by eksperimental** [comment]
UPDATE: I have removed the mention to "functional combinators" as they are not explained.

**Comment by doomspork** [comment]
@eksperimental there is no documentation around the lesson versioning, it's something we've only recently rolled out, we need to update the README to include mention of that version 👍

**Comment by eksperimental** [comment]
@doomspork: thank you. I'm updating the PATCH version for typos, or links or backticks, changes that do not introduce any new content.
MINOR for any new addition.
MAJOR your call.

**Comment by doomspork** [comment]
@eksperimental that is essentially what we've been following.  A major change hasn't occurred yet but that might be something like a total re-write.

**Comment by eksperimental** [comment]
great then. good to hear

**Pull request merged**
