### PR TITLE
Updating Index of Portuguese(Brazil)

### PR DESCRIPTION
**Pull request by pragmaticivan**
* Removing Extra pt Link from `en` index.
* Updating `pt` index and following the `en` index format.

Related to #89

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @pragmaticivan!  @tiagobarreto if you have a moment, could you look at these changes?

**Comment by tiagobarreto** [comment]
@doomspork yeah, sure! :+1:

**Comment by pragmaticivan** [comment]
Any feedback?

**Comment by pragmaticivan** [comment]
I have 7 Pull Requests now

**Comment by tiagobarreto** [comment]
All revised, ok. :+1:

**Comment by tiagobarreto** [comment]
All revised, ok. :+1:

**Comment by doomspork** [comment]
Thank you @tiagobarreto for taking the time to look these over.

Big thank you to @pragmaticivan! 

Would you mind telling me your Twitter handles?  When I tweet about these lessons I'd like to give credit.

**Comment by pragmaticivan** [comment]
https://twitter.com/pragmaticivan @doomspork

**Comment by doomspork** [comment]
Thank you very much for all your help @pragmaticivan

**Pull request merged**
