### PR TITLE
New lessons and UI updates

### LINKED ISSUE #27: Missing Supervisor code on Ecto migrations example
In the chapter about `Ecto`, specifically in `Migration` topic, I think that you miss explaining the `Supervisor` part. When we generate an `mix` application without `--sup`  we don't get the `Supervisor` code and we must put it manually and if you try to run the migrations the code doesn't run.

https://github.com/elixir-lang/ecto/blob/master/examples/simple/lib/simple.ex#L4

Maybe you skipped this part but I think that is important to show :)

### PR DESCRIPTION
**Pull request by doomspork**
This PR includes a number of changes including new lessons:

+ New OTP Concurrency lesson
+ New OTP Supervisor lesson
+ New Executable lesson
+ Updates to the Erlang Interoperability lesson
+ Updates to the Ecto lesson (Closes #27)
+ Refactor generation of the sidebar
+ Add collapsible sections to the sidebar

### CODE REVIEW

**Comment by doomspork** [comment]
@luizvarela here are some new lessons and updates to the Ecto lesson as you reported.  Let me know your thoughts.  If necessary I can deploy these changes to make it easier to go through the content, just let me know.

Thanks again for your feedback :+1:

**Comment by luizvarela** [comment]
Nice @doomspork, but I can't find the updates to the Ecto lesson, I saw that you created OTP Supervisors into a lesson, but would be better if you put the Supervisor configuration into the Ecto lesson.

This line here:
https://github.com/elixir-lang/ecto/blob/master/examples/simple/lib/simple.ex#L4

**Comment by doomspork** [comment]
Sorry @luizvarela I missed a commit.  See the Ecto supervisor changes here: https://github.com/doomspork/elixir-school/blob/otp-and-escripts/lessons/specifics/ecto.md

**Comment by luizvarela** [comment]
:+1:  Nice @doomspork, now can be merged.

**Comment by doomspork** [comment]
Glad you like the changes @luizvarela!  I'm going to give this all another once over and then get it published tonight.

Thanks again for your feedback. :+1:

**Pull request merged**
