### PR TITLE
Update the GenStage examples for v0.11

### PR DESCRIPTION
**Pull request by nurugger07**
This PR updates the examples in the GenStage advanced lesson. It includes a version bump for GenStage and removal of invalid code in the examples.

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @nurugger07, this is great!   Would you mind applying this change to the translated GenStage lessons?

**Comment by nurugger07** [comment]
@doomspork looks like I got all the files now :)

**Comment by doomspork** [comment]
Thank you @nurugger07!

**Comment by nurugger07** [comment]
@doomspork no problem :)

**Pull request merged**
