### PR TITLE
[Jp] typespec.md translation

### PR DESCRIPTION
**Pull request by HirofumiTamori**
Added typespec.md translation.

### CODE REVIEW

**Comment by nscyclone** [comment]
@hinamiyagk, @3100, could you, please, review this one?

**Comment by hinamiyagk** [comment]
I see, but I don't have time now. I'll do it later.

**Comment by riseshia** [comment]
Please apply this #653

**Comment by 3100** [comment]
@HirofumiTamori Sorry for the late reply. This looks good to me. As @riseshia mentioned, would you check #653 and update this PR?

**Comment by hinamiyagk** [comment]
This looks good to me too.

**Comment by doomspork** [comment]
Thank you @HirofumiTamori, @hinamiyagk and @3100 🎉

**Pull request merged**
