### PR TITLE
[NO] Translation of modules and mix.

### PR DESCRIPTION
**Pull request by therobinsj**

### CODE REVIEW

**Comment by doomspork** [comment]
This is great @therobinsj!  I forget, is there anyone you'd like to have review this before we merge?

**Comment by therobinsj** [comment]
@Devalo has reviewed the "modules" lesson. But, he haven't had the time to read through the "mix" lesson yet.

**Comment by Devalo** [comment]
Sorry, I've been a bit busy. I'll see if I can read through the mix part today.

**Comment by therobinsj** [comment]
Both lessons reviewed by @Devalo, ready to be merged :)

**Comment by doomspork** [comment]
Thank you @therobinsj and @Devalo!!

**Pull request merged**
