### PR TITLE
[FR] Improve the explanation of pattern matching

### PR DESCRIPTION
**Pull request by jumichot**
Hello !
This is the french translations for the original changes in #808.
Feedback welcome ;)

### CODE REVIEW

**Comment by nscyclone** [comment]
@julienXX, could you take a peek at this, please?

**Comment by jumichot** [comment]
Thanks for the review @julienXX , I made the changes

**Comment by julienXX** [comment]
@nscyclone good to merge for me :)

**Comment by nscyclone** [comment]
Thanks, @jumichot and @julienXX!

**Pull request merged**
