### PR TITLE
Reordered lessons / Removed Best Practices

### PR DESCRIPTION
**Pull request by pjhampton**
References #118

### CODE REVIEW

**Comment by doomspork** [comment]
Hi @joneslee85, @pragmaticivan, @jesusangelm, and @cizixs!  First and foremost, thank you all for your help with translations.  In an effort to keep everyone in the loop, I wanted to call your attention to this PR.  It re-orders the basic lessons in your languages and introduces a new Sigil lesson.

Any questions or concerns with these changes?

**Comment by pragmaticivan** [comment]
My considerations about the PR: the translations where we don't have the `pipe` lesson translated seems to be wrong, and also you added a file for the `pipe lesson` without translated data inside the folder `/pt`

The Best Practices update seems to be solid.

Not sure how we supposed to solve this order problem in case we don't have the `pipe` lesson.

**Comment by pragmaticivan** [comment]
What about instead of using the order from the list here, just using a count variable?

```

**Comment by doomspork** [comment]
@pragmaticivan if you want to test out that change and open a PR I'd be glad to look at it, sounds like a solid suggestion :+1:

**Comment by doomspork** [comment]
@pragmaticivan do you want to remove the empty pt/pipe lesson for now?  I believe some of the other translators were using English placeholders which may have been @pjhampton's rationale.

**Comment by pjhampton** [comment]
I agree with @doomspork, @pragmaticivan. The problem is translators from different languages have different ways of doing things. For example, the vietnamese translators duplicate all the english lessons and translate over them. However, if you would like an exception for pt, feel free to let me know :smile_cat:

**Comment by pragmaticivan** [comment]
In this case I would suggest having a flag such as ` to be translated` with a link for this file on github, or something like that.

**Comment by doomspork** [comment]
That's an interesting idea @pragmaticivan.  I think a placeholder with a notice that the file needs translation and a link to the repo would be a good solution.  Thoughts @pjhampton?

**Comment by doomspork** [comment]
@joneslee85 you've used English lesson placeholders, do you have any thoughts?

**Comment by pjhampton** [comment]
I'm impartial guys to be honest as I don't really ever deal with the translations, just new English lesson content. 

It may be best to let the invisible hand guide this one, and let the language translators work to the workflow they wish within their language, rather than unifying an approach? If we are creating an approach it could be good to update
https://github.com/doomspork/elixir-school/wiki/Translating - with a more refined setup process for a new language.

A placeholder statement on an English lesson might be a good idea, but again, I'm neutral on this enhancement.

**Comment by doomspork** [comment]
Alright.  @pjhampton for the time being will you remove the pt lesson?  We can leave the others and make changes once we incorporate the count change that @pragmaticivan suggested.

**Comment by pjhampton** [comment]
@pragmaticivan @doomspork: I reverted any changes to pt. Let me know if any issues.

**Comment by doomspork** [comment]
Looks good to me @pjhampton.  @pragmaticivan unless you have any addition thoughts I'm going to merge this :grinning:

**Comment by pragmaticivan** [comment]
@doomspork go for :D We're going to add the last one on basic, so we can update the order again.

**Pull request merged**
