### PR TITLE
=BG= :crypto.strong_rand_bytes 3

### PR DESCRIPTION
**Pull request by bguiz**
previously was :crypto.rand_bytes 3
and this has been superseded: http://erlang.org/doc/man/crypto.html#strong_rand_bytes-1

### CODE REVIEW

**Comment by doomspork** [comment]
Howdy @bguiz!  Could you apply this change to the other translations where applicable?  😁

**Comment by bguiz** [comment]
OK, I'll give it a shot. It'll just be a grep/ sed job though- cos I don't understand those languages!

**Comment by bguiz** [comment]
OK, I'll give it a shot. It'll just be a grep/ sed job though - cos I don't understand those languages!

**Comment by doomspork** [comment]
That's perfectly acceptable @bguiz 😁

**Comment by doomspork** [comment]
Howdy @bguiz, no rush but any update on this PR?  Would you like one of us to take a whack at updating the other examples?  😀

**Comment by bguiz** [comment]
Hey there, been busy - only just got around to it now. PR has been updated!

**Comment by doomspork** [comment]
No worries @bguiz, just checking in!  Thank you so much for your contribution, much appreciated!  Have a great Sunday Funday 😁

**Pull request merged**
