### PR TITLE
Embedded elixir translate to spanish

### PR DESCRIPTION
**Pull request by jesusangelm**

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @jesusangelm!  

@erickgnavar or @milmazz could you look this over?  Thank you!

**Comment by erickgnavar** [comment]
looks good, thanks @jesusangelm

**Comment by doomspork** [comment]
Great thank you @erickgnavar.  @jesusangelm once you squash your commits this will be good to merge.

Thank you for helping out :+1:

**Comment by jesusangelm** [comment]
@doomspork commits squashed

**Comment by doomspork** [comment]
Thank you again @jesusangelm :+1:

**Pull request merged**
