### PR TITLE
[PL] Translation of erlang interop lesson

### PR DESCRIPTION
**Pull request by Koziolek**
In scope of issue #202

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @Koziolek!  cc @kdebowski for review

**Comment by nscyclone** [comment]
You may use automatic TOC generation as was described [here](https://github.com/doomspork/elixir-school/pull/352#issuecomment-218850807).

**Comment by kdebowski** [comment]
@Koziolek it's OK

**Comment by doomspork** [comment]
Thanks guys 😀

**Pull request merged**
