### PR TITLE
Add ID translation for #529

### PR DESCRIPTION
**Pull request by christiansakai**

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @christiansakai!  @rezaprima could you look at this when you have a chance?

**Comment by rezaprima** [comment]
I'm sorry, this one conflicts with my translation. But mine addresses the arity change (from `chunk_by` to `chunk_by/2`) mentioned in https://github.com/doomspork/elixir-school/compare/master...improvement/add_arity_to_enum_chunk_by_basics#diff-da9b21c2c73f7335cedc97aa18d36b0cR53

**Comment by doomspork** [comment]
@christiansakai can you resolve the conflict or close the PR if it's no longer necessary?  Thank you!

**Comment by christiansakai** [comment]
@rezaprima translation is more updated, so I'll close mine.

**Pull request closed without merging**
