### PR TITLE
Update gen-stage.md

### PR DESCRIPTION
**Pull request by gemantzu**
@kosmas could you take a look at this file and propose a better translation for `sink`? Thanks!

### CODE REVIEW

**Comment by Kosmas** [comment]
@gemantzu Sorry just noticed this was about the sink in the text.
I would probably translate it as 'προορισμός'

Source - Sink
Πηγή - Προορισμός

**Comment by gemantzu** [comment]
Ok, I'm going to edit this now, I like it way better than what I did in the original translation. Thanks!

**Comment by Kosmas** [comment]
@gemantzu looks good!
:+1

**Comment by doomspork** [comment]
Thanks you two!  Awesome work.

**Pull request merged**
