### PR TITLE
[CN] update basics

### PR DESCRIPTION
**Pull request by Cifer-Y**

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @Cifer-Y!

@cizixs could you give this a look when you have a moment?

**Comment by Cifer-Y** [comment]
append update for basics/collections

**Comment by Cifer-Y** [comment]
append update basics/enum.md to 1.0.0

**Comment by cizixs** [comment]
@Cifer-Y Thanks for your contribution. And this update looks great to me!

ping @doomspork

**Pull request merged**
