### PR TITLE
Remove Concoction project references

### PR DESCRIPTION
**Pull request by Zahidul-Islam**

### CODE REVIEW

**Comment by doomspork** [comment]
I swore I replaced all of these before, thank you @Zahidul-Islam 👍

**Comment by doomspork** [comment]
@Zahidul-Islam could you see if these changes should be made in any of the other languages?

**Comment by Zahidul-Islam** [comment]
@doomspork all translations have Concoction reference

**Comment by doomspork** [comment]
@Zahidul-Islam if you'd like to submit a PR for those change it would be wonderful.  If not, I can tackle it later this week.

**Pull request merged**
