### PR TITLE
ES-392 fix Fixes the bad output and removes complexity on advanced/escript lesson

### PR DESCRIPTION
**Pull request by setzer777**
Addresses issue [392](https://github.com/doomspork/elixir-school/issues/392)

### CODE REVIEW

**Comment by doomspork** [comment]
@setzer777 does this change need to be made to any other languages?

@aleandros thoughts?

**Comment by setzer777** [comment]
@doomspork Already made the changes to all the languages, I forgot it at the beginning haha

**Comment by aleandros** [comment]
Great! I can add the change to the spanish translation before it's merged

**Comment by pjhampton** [comment]
LGTM 😄  thanks @setzer777 and @aleandros

**Comment by doomspork** [comment]
This is great, thank you @setzer777 and @aleandros 👍

**Pull request merged**
