### PR TITLE
[en] small fix in umbrella-projects.md / Child projects

### PR DESCRIPTION
**Pull request by yuriibodarev**
## Child projects
`machine_learning_toolkit/app` misses one last letter in a dir name: `machine_learning_toolkit/apps`

### CODE REVIEW

**Comment by doomspork** [comment]
@yuriibodarev could you see if this issue is present in any of the other languages?

**Comment by yuriibodarev** [comment]
I think the same issue is present in **[ID]**, **[JP]**, **[PL]** and **[PT]** translations.
I can add fixes to this same pull request, it's only 1 letter... or we need to create a new PR for each language separately?

**Comment by doomspork** [comment]
@yuriibodarev adding those changes to this PR is sufficient, thank you for double checking 👍

**Comment by yuriibodarev** [comment]
@doomspork PR updated with corrections for other languages

**Comment by nscyclone** [comment]
Thanks, @yuriibodarev!

**Pull request merged**
