### PR TITLE
BN Translation of Enum chapter

### PR DESCRIPTION
**Pull request by prio101**
@code-shoily and @masnun please review this Pull Request

### CODE REVIEW

**Comment by masnun** [comment]
Looks good to me

**Comment by prio101** [comment]
Thanks @masnun Brother.

**Comment by code-shoily** [comment]
The translation looks good. There are some minor typos which I guess can be polished up later. I'd say it can be merged :) 

And thanks @prio101

**Comment by prio101** [comment]
Thanks to @code-shoily Brother . So, @doomspork can do something about it now.

**Comment by doomspork** [comment]
Thank you @prio101, @code-shoily and @masnun!

**Comment by masnun** [comment]
Thank you!

**Pull request merged**
