### PR TITLE
Use relative links in all lessons

### PR DESCRIPTION
**Pull request by brain-geek**
When reviewing the #736 I've noted that this lesson uses an absolute link to other lessons.

I think that having those links relative will help translators a bit + we already use this approach in the majority of links across the site.

### CODE REVIEW

**Comment by nscyclone** [comment]
Nice catch, @brain-geek!
I've also found ~30 occurrences of absolute paths. Shouldn't we fix them all in a single shot? If so, searching for `)[/` might be a good start.
This could also be mentioned in `CONTRIBUTING` when it will be updated.

**Comment by brain-geek** [comment]
@nscyclone Thanks for the idea, I'll look into it and change the PR accordingly.

**Comment by brain-geek** [comment]
Commited also all other names.

Looks like the majority of those links were in places where english version had absolute links.

Not sure whether we should add one more point to `CONTRIBUTING`.

**Comment by doomspork** [comment]
This is awesome @brain-geek!

**Comment by brain-geek** [comment]
@doomspork Does this look OK for you to merge? :)

**Comment by doomspork** [comment]
@brain-geek done!

**Pull request merged**
