### PR TITLE
[KO] Translation of Testing lesson

### PR DESCRIPTION
**Pull request by devleoper**
related: #201

I applied some feedbacks from @dalgona.

You can compare the trasnlated text with the original text at devleoper/elixir-school#1

This PR is ready for review. :rocket:

### CODE REVIEW

**Comment by devleoper** [comment]
I mistyped a number of chapter on the commit message, please don't take care of them:oops:

**Comment by doomspork** [comment]
@devleoper it's okay with me.  If for future reference you'd like to learn how to reword a previous commit message (using `git rebase -i`), I'd be help to walk you through it 😀

**Comment by devleoper** [comment]
@doomspork Now I fixed the commit message. Thank you so much! I'm glad to use awesome things of git.

**Comment by doomspork** [comment]
Great @devleoper!  Feel free to merge this whenever you're happy 👍

**Comment by devleoper** [comment]
@doomspork Basic lessons are almost translated so I'm going to merge when all of the Basic lessons are translated (and reviewed). 😉

**Comment by doomspork** [comment]
Sounds good @devleoper!

**Pull request merged**
