### PR TITLE
FIX: Removed redundant dict ref.

### PR DESCRIPTION
**Pull request by pjhampton**
As recommended by @julienXX in #232

### CODE REVIEW

**Comment by julienXX** [comment]
👍 I would also remove the Dict module mention in the Keyword list paragraph.

**Comment by brain-geek** [comment]
Looks good

**Comment by pjhampton** [comment]
@brain-geek ~ Can you do this too from RU, please Oleksandr?

**Comment by brain-geek** [comment]
@pjhampton Ru version is in #245 .

**Comment by pjhampton** [comment]
Thanks @brain-geek!

**Pull request merged**
