### PR TITLE
es Feature/update enum lesson to v1.0.0

### PR DESCRIPTION
**Pull request by edwinallenz**
Complete translation review and update for lessons/enum.md to spanish

### CODE REVIEW

**Comment by edwinallenz** [comment]
@erickgnavar si puedes darle un vistazo y me cuentas si esta gramaticalmente bien

**Comment by edwinallenz** [comment]
Just updated this PR from master branch
@erickgnavar let me know if you can check this.

**Comment by doomspork** [comment]
@edwinallenz looks like there is still a merge conflict.  Let me know if you'd like a hand getting it resolved 👍

**Comment by edwinallenz** [comment]
@doomspork I merged with a local version of master branch without any conflicts, are you sure or I'm missing something?

**Comment by doomspork** [comment]
@edwinallenz hmm, I can't merge.  I think you're merging your fork's master into your branch but your master may not be up-to-date.

You could try something something like this:

```shell
$ git remote add upstream git@github.com:doomspork/elixir-school.git
$ git fetch -- all
$ git checkout feature/update_enum_lesson
$ git rebase upstream/master
```

If you run into problems, feel free to ping me on Elixir Slack 😀

**Comment by edwinallenz** [comment]
@doomspork it's done, let me know if it works.

**Comment by doomspork** [comment]
Thank you @edwinallenz!

**Pull request merged**
