### PR TITLE
Use pessimistic versioning to allow 2.3.x versions of ruby.

### LINKED ISSUE #739: Is ruby 2.3.0 required
The latest stable release of ruby is `2.3.1` yet the `Gemfile` indicates that you must use [2.3.0](https://github.com/doomspork/elixir-school/blob/master/Gemfile#L2).
Can that be changed to `~> 2.3.0` so `2.3.1` can be used to run the Jekyll app?

### PR DESCRIPTION
**Pull request by et**
Fixes #739

### CODE REVIEW

**Comment by ybur-yug** [comment]
LGTM, merging

**Comment by ybur-yug** [comment]
Thanks @et!

**Comment by doomspork** [comment]
Evidently this isn't something Heroku appreciates so we'll need to switch to using `2.3.1`.

**Comment by et** [comment]
@doomspork should this be reverted?

**Comment by doomspork** [comment]
@et I pushed a change to master when I was testing what Heroku supported.  We're good 👍

**Pull request merged**
