### PR TITLE
[BN] Translated the lesson on `Modules`

### PR DESCRIPTION
**Pull request by code-shoily**
Please check for correctness @masnun @prio101

### CODE REVIEW

**Comment by prio101** [comment]
Looks great to me @code-shoily vai ...

**Comment by masnun** [comment]
Looks good!

**Comment by code-shoily** [comment]
@doomspork I think we're good to merge on this one.

**Comment by nscyclone** [comment]
Thanks, @code-shoily, @prio101 and @masnun!

**Pull request merged**
