### PR TITLE
[it] add basics/*.md translations (refers #197)

### PR DESCRIPTION
**Pull request by apeacox**
two more translations for #197 🎉

### CODE REVIEW

**Comment by doomspork** [comment]
Wow @apeacox this is amazing!  Are you ready for this to merge in or do you want to hold off?

**Comment by apeacox** [comment]
Yes! They can be merged. Maybe I missed some small typo, but the committed translations are completed. I will continue the remaining lessons in the next days ;-)

**Comment by doomspork** [comment]
Awesome! 

@apeacox would you be interested in being our point-of-contact for Italian translations?  I can add you to the repo so you can merge other Italian translations when they're ready.  I only ask that you not push to master directly; with PRs we ensure all the contributors get a chance to provide feedback.

**Comment by apeacox** [comment]
Sure! I'm available for this ✌🏻️

Thank you for merging my PR

**Comment by doomspork** [comment]
Thank you for all your help @apeacox :grinning: 

Added!

**Comment by doomspork** [comment]
@apeacox what is your twitter handle?

**Comment by apeacox** [comment]
Thank you for adding me to the project 😊

My twitter handle is @apeacox

**Pull request merged**
