### PR TITLE
[JP] Add custom Mix task lesson

### PR DESCRIPTION
**Pull request by hinamiyagk**
#49 
I can't understand meaning of `shipping our application` enough so review is welcome.

### CODE REVIEW

**Comment by doomspork** [comment]
@hinamiyagk "shipping our application" is another way of saying deploying or distributing the application.

@3100 could you take a look at this?

**Comment by christiansakai** [comment]
@doomspork just a translation question related. What is the general guidelines for translation? Because it is hard to translate word by word, and if it does, seems like it is more confusing to read it in the translated language rather than in English.

**Comment by doomspork** [comment]
@christiansakai I believe other translators translate the overall meaning but change the verbiage to fit in their language.

**Comment by christiansakai** [comment]
@doomspork thanks! good to know

**Comment by doomspork** [comment]
You're welcome @christiansakai, thanks for your help 👍

**Comment by doomspork** [comment]
Thank you again @hinamiyagk 👍

**Pull request merged**
