### PR TITLE
[ES] Translation of concurrency lesson

### PR DESCRIPTION
**Pull request by aleandros**

### CODE REVIEW

**Comment by aleandros** [comment]
@erickgnavar @setzer777 It would be great if you can proof read it. Thanks in advance!

**Comment by setzer777** [comment]
Man, you are in fucking fire haha ill check it tomorrow morning. :)

**Comment by doomspork** [comment]
Thank you so much @aleandros, you're killing it 👍

**Comment by doomspork** [comment]
@setzer777 were you able to review these changes?

**Comment by doomspork** [comment]
Thank you @aleandros, sorry for the delays!  If there's any feedback the other translators have they can submit a new PR 😀

**Pull request merged**
