### PR TITLE
Translate advanced section into Chinese.

### PR DESCRIPTION
**Pull request by cizixs**
Hey, I finished the advanced section translation. 
Please review the commit, and feel free to merge.

### CODE REVIEW

**Comment by doomspork** [comment]
Hi @cizixs!  This looks great.  Did you get a chance to see PR #69?

On a separate note: Would you be interested in being the point-of-contact for the Chinese translations?  I'd be glad to add you to the repo as a contributor so you can manage Issues/PRs for the Chinese translations.  My only request is major changes go through PRs :grinning:

**Comment by doomspork** [comment]
Also are you on Twitter?  If so, what is your handle?  When I tweet about these translations I'd be glad to tag you :grinning:

**Comment by cizixs** [comment]
@doomspork It is my honour to be point-of-contact for the Chinese translations. I sure can help review and merge Chinese translations. Only I need some tutorial on how to get started.

**Comment by cizixs** [comment]
@doomspork I do have  a twitter account at https://twitter.com/cizixs.

And thanks for your appreciation.

**Comment by doomspork** [comment]
@cizixs a tutorial for which parts?  Always glad to help :smile:

**Comment by cizixs** [comment]
@doomspork, I just need to know if there is a notification mechanism that reminds me there is a PR assigned to me, or I just look through the PRs every day?

**Comment by doomspork** [comment]
I'll ping you on all Issues/PRs I think you should know about.  I think if you watch the repos you'll see all of the activity in your notifications.

**Comment by cizixs** [comment]
@doomspork OK. That will do. Always glad to help.

**Pull request merged**
