### PR TITLE
[BN] Added the chapter on List Comprehension

### PR DESCRIPTION
**Pull request by code-shoily**
Added the chapter for List Comprehension. @masnun and @prio101 as usual, calling you out for a check :)

### CODE REVIEW

**Comment by prio101** [comment]
Looks Great to me :smile: @code-shoily vai

**Comment by prio101** [comment]
@code-shoily by the way .... Who is that @mafinar here :clipboard: ??

**Comment by code-shoily** [comment]
@prio101 Git Author issue, don't worry about it. You know that both are me! :P

**Comment by masnun** [comment]
:+1:

**Comment by code-shoily** [comment]
@doomspork I think we're good to merge on this one.

**Comment by nscyclone** [comment]
Thanks, @code-shoily, @prio101 and @masnun!

**Pull request merged**
