### PR TITLE
[BN] Translated the lessons on String

### PR DESCRIPTION
**Pull request by code-shoily**
@masnun and @prio101 did the String chapter. I think we'll need to get back to it later and enrich it more, feels incomplete when re-read.

### CODE REVIEW

**Comment by prio101** [comment]
Looks good to me

**Comment by code-shoily** [comment]
Wow, in less than a minute? Dude you read fast :O @prio101

**Comment by prio101** [comment]
@code-shoily via  yes!! ... side effect of reading EULA...

**Comment by ybur-yug** [comment]
Thanks @code-shoily @prio101! You folks are cranking stuff out :) <3

**Pull request merged**
