### PR TITLE
Fix mis-spelling of 'oops' in Plug lesson

### PR DESCRIPTION
**Pull request by GregMefford**

### CODE REVIEW

**Comment by doomspork** [comment]
@GregMefford could you see if this change needs to be made in other languages as well?  Thank you 👍

**Comment by GregMefford** [comment]
I bet it does. I'll check and update the PR.

**Comment by GregMefford** [comment]
I've updated the PR to include all the languages that have the Plug lesson translated.

As an aside, I noticed that there's a `vi` language, which is actually English but with very minor grammatical differences between it and the main English version. Is this intended to be a translation for the US Virgin Isles, or maybe it was a mistake made by someone using Vim as an editor?

**Comment by devleoper** [comment]
`vi` stands for Vietnamese. I think these translators just copied all of English lessons before starting translation.

**Comment by doomspork** [comment]
What @devleoper said is correct 😀

**Comment by doomspork** [comment]
Thank you @GregMefford 👍

**Pull request merged**
