### PR TITLE
[JP] Update translation in 'basics/collections'

### PR DESCRIPTION
**Pull request by hinamiyagk**
* Remove topics about dictionary(deprecated)
* Elixir 1.2 updates

### CODE REVIEW

**Comment by hinamiyagk** [comment]
#49

**Comment by doomspork** [comment]
Thank you @hinamiyagk!  @3100 if you have a moment, could you look this one?

**Comment by 3100** [comment]
Looks good to me. Thank you for the update!

**Comment by doomspork** [comment]
Thank you @hinamiyagk and @3100 👍

**Pull request merged**
