### PR TITLE
 Improve translation(jp) of Enum session

### PR DESCRIPTION
**Pull request by riseshia**
From #753

### CODE REVIEW

**Comment by doomspork** [comment]
This is great @riseshia!  Would you like anyone to review this or are you happy with merging it?

**Comment by riseshia** [comment]
I can't find who is the maintainer of jp..OTL
could @hinamiyagk or @marocchino review this?

**Comment by doomspork** [comment]
@3100 has been doing most of the Japanese translation.  @3100 if you have a moment could you take a peek at this?  😀

**Comment by marocchino** [comment]
@riseshia : Agree with @doomspork I am not sure with confirming this by myself.

**Comment by 3100** [comment]
@doomspork Sure.
@marocchino Thank you! LGTM!

**Comment by doomspork** [comment]
Thank you all!!

**Pull request merged**
