### PR TITLE
[JP] Translation of Sigils Lesson

### PR DESCRIPTION
**Pull request by HirofumiTamori**
I translated a short chapter, **Sigils** lesson into Japanese.

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @HirofumiTamori!  @3100 could you look at this when you have a moment?

**Comment by hinamiyagk** [comment]
I found some mistakes:

* change `lang: ja` to `lang: jp` in `sigils.md` (in this project, `jp` is used for japanese language code)
* change `order: 10` to `order: 11` in `testing.md` (there is the conflict of article order between sigils and testing lesson now)

**Comment by HirofumiTamori** [comment]
@hinamiyagk Thanks for your review.

**Comment by 3100** [comment]
This is awesome.

**Comment by 3100** [comment]
@HirofumiTamori  @hinamiyagk Thank you so much :+1:

**Pull request merged**
