### PR TITLE
Add arity to functions in EEx lesson

### PR DESCRIPTION
**Pull request by brain-geek**
Right now we have arity in all function mentions. This PR adds arity to function names in EEx lesson.

### CODE REVIEW

**Comment by brain-geek** [comment]
@nscyclone Can you look through this one? Just for verification.

**Comment by nscyclone** [comment]
This is a nice catch, @brain-geek! It's totally fine but I'm afraid the fix should applied to every existing translation (`es`, `id`, `ko`, `pl`, `pt`, `vi`) and the pending `ru` translation as well.

**Comment by brain-geek** [comment]
@nscyclone Thanks for noting! I've fixed all existing translations + ru in separate PR.

**Comment by doomspork** [comment]
This is great, thank you @brain-geek and @nscyclone!

**Pull request merged**
