### PR TITLE
Self host Entypo for social buttons

### PR DESCRIPTION
**Pull request by burden**
This update puts Entypo into the repo for self hosting, in hopes that third-party browser add-ons no longer block the icons in production.

### CODE REVIEW

**Comment by doomspork** [comment]
@veverkap / @pragmaticivan, is this what you were expecting to fix the issue?

**Comment by veverkap** [comment]
Yes this is exactly it

On Saturday, April 16, 2016, Sean Callan <notifications@github.com> wrote:

> @veverkap <https://github.com/veverkap> / @pragmaticivan
> <https://github.com/pragmaticivan>, is this what you were expecting to
> fix the issue?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/doomspork/elixir-school/pull/288#issuecomment-210835765>
>


-- 
Sent from Gmail Mobile

**Comment by doomspork** [comment]
That was :zap: fast @veverkap, thanks!

**Comment by doomspork** [comment]
Pushed to Heroku and it does appear to do the trick.  

Just to note, and I don't think there's anything we can do, the icons are still blocked by uBlock Origin in Chrome if you've selected certain social blocking.

**Comment by doomspork** [comment]
Thank you @burden :+1:

**Pull request merged**
