### PR TITLE
[On #72] Translate plug.md into Chinese

### PR DESCRIPTION
**Pull request by AquarHEAD**
@cizixs please review if you have time :smile:

### CODE REVIEW

**Comment by cizixs** [comment]
Cool, LGTM!

**Comment by doomspork** [comment]
Thank you @AquarHEAD and @cizixs :+1:

**Comment by doomspork** [comment]
@AquarHEAD what is your twitter handle?  Apologizes if I've asked previously.

**Comment by AquarHEAD** [comment]
@doomspork just [aquarhead](https://twitter.com/aquarhead) :D

**Pull request merged**
