### PR TITLE
Basics lessons spanish translation

### PR DESCRIPTION
**Pull request by erickgnavar**

### CODE REVIEW

**Comment by doomspork** [comment]
Great @erickgnavar!  Is this ready to be merged?

**Comment by erickgnavar** [comment]
This PR only contains 2 translated lessons, let me finish the whole **basics** section to make the merge.

**Comment by doomspork** [comment]
Sounds good.

**Comment by doomspork** [comment]
@erickgnavar thanks for pushing up those new lessons!

Would you mind rebasing your branch to remove those extra merge commits?  I gave it a whirl locally and there was only a minor merge conflict with the `_config.yml`.  Something like this should do the trick:

```shell
$ git rebase -i --autosquash --autostash upstream/master
```

**Comment by erickgnavar** [comment]
Done

**Comment by doomspork** [comment]
Thanks @erickgnavar.  You didn't need to squash them all, sorry if I didn't explain that well.  Was just aiming to rebase out the two merge commits from pulling in the upstream.  No worries though.

Thanks again for your help with everything, much appreciated :grinning:

**Pull request merged**
