### PR TITLE
Commented lines translated enum.md

### PR DESCRIPTION
**Pull request by RTJ**
Commented lines translated into Spanish

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://elixirschool.rtj-patch-1.doomspork-elixir-school-3c64f857cd94b93cd0cf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://elixirschool.rtj-patch-1.doomspork-elixir-school-3c64f857cd94b93cd0cf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by doomspork** [comment]
@jesusangelm / @erickgnavar could one of you verify this change?  Thanks!

**Comment by erickgnavar** [comment]
Looks good, @RTJ is possible join #256 and #257 in one single PR? I say because because both have the same purpose.

**Comment by jesusangelm** [comment]
Looks great for me!

**Pull request merged**
