### PR TITLE
Japanese translation

### PR DESCRIPTION
**Pull request by 3100**
cf. #33  

Please do not merge yet.

### CODE REVIEW

**Comment by doomspork** [comment]
Awesome work @3100 :+1:

When this is ready I'll merge and add you to the repo as well

**Comment by 3100** [comment]
It is done.

**Comment by doomspork** [comment]
Very cool @3100!  Are you ready for me to merge (and deploy)?

**Comment by 3100** [comment]
Yes, please merge and deploy.

**Comment by 3100** [comment]
Thanks!

**Comment by doomspork** [comment]
Done!  I've also added you to the repo so you can help maintain the Japanese translations.

Thank you again @3100!!

**Comment by 3100** [comment]
Sure. If some changes are needed, should I commit and push them to a new branch, or simply do them to the master?

**Comment by doomspork** [comment]
Master is fine for small changes.  For big changes (new lessons, reformatting, etc) I think a PR is best.  Sound good?

**Comment by doomspork** [comment]
I will keep you informed of any changes to the lessons so you can determine if translation is necessary.  

I'm going to work on a few new ones this week.

**Comment by 3100** [comment]
> Master is fine for small changes. For big changes (new lessons, reformatting, etc) I think a PR is best.
> Sound good? 

Yes, thanks. I will keep it in mind.

> I'm going to work on a few new ones this week.

It's great! I am looking forward to them.

**Pull request merged**
