### PR TITLE
[JP] Add description of special syntax of map

### PR DESCRIPTION
**Pull request by hinamiyagk**
Apply #452 changes to Japanese translation

### CODE REVIEW

**Comment by hinamiyagk** [comment]
#481

**Comment by doomspork** [comment]
Thank you @hinamiyagk!  @3100 could you take a peek at these changes?

**Comment by 3100** [comment]
@hinamiyagk Thank you!

**Comment by doomspork** [comment]
Thank you @hinamiyagk and @3100! 👍

**Pull request merged**
