### PR TITLE
First version of russian glossary

### PR DESCRIPTION
**Pull request by brain-geek**
In the discussion of issue #162 there was a lot of positive feedback about creating glossary. This is the first version of it with all terms I've found yet.

I'm not sure whether it should be separate file per language or one file for everything in the root folder - that needs to be discussed.

### CODE REVIEW

**Comment by doomspork** [comment]
This is awesome @brain-geek.  Is it possible for you to squash some of these commits?

Do you think this is strictly useful for translators or would this be something a reader might want to peruse?  If the latter, we should figure out a place to link to this from the website.

**Comment by brain-geek** [comment]
@doomspork That's very good question. Actually, readers of translated versions may be interested in what are original terms used. But that is not a major use case, as those experienced people will be reading original english version anyway. 

So, I don't think why would we link it on the site.

I'll squash last commits.

**Comment by doomspork** [comment]
Sounds good @brain-geek :+1:

**Comment by doomspork** [comment]
@pragmaticivan and @pjhampton, any thoughts?

**Comment by pjhampton** [comment]
This LGTM :+1:. Can we change this PR to reflect that it is the Russian Glossary in the title?

**Comment by doomspork** [comment]
Thinking about this a little more, I want to offer some suggestions and see what everyone thinks.

First thing, do we need this under source control?  If not, this might be better in the Wiki.  There we can setup individual glossaries for each language.

If we do need it under source control, should we be maintaining one large glossary for all languages or individual files per language?  (eg `glossary.md` -> `/glossary/ru.md`)

**Comment by pragmaticivan** [comment]
Once it will be always one page, maybe we can "create an example" of how it would fit there first.

**Comment by brain-geek** [comment]
> First thing, do we need this under source control? 
As for me, that makes sense under version control due to the fact that better term translations pop up - and this leads to glossary change.

Some terms (like 'pattern matching') changed their russian translation 3-4 times before getting to current state.

> If we do need it under source control, should we be maintaining one large glossary for all languages or individual files per language?
That's a good question and I don't know an answer to it. My suggestion is to start with global file and see how it goes.

**Comment by brain-geek** [comment]
> Can we change this PR to reflect that it is the Russian Glossary in the title?

Done

> Is it possible for you to squash some of these commits?

Done

**Comment by doomspork** [comment]
@brain-geek sounds good.  We'll start with this glossary and go from there.

Thanks again!

**Pull request merged**
