### PR TITLE
[JP] Add translation of pipe operator lesson

### PR DESCRIPTION
**Pull request by hinamiyagk**
#49 

I'm not sure about translations of some words.
examples:
* `So messy in fact that function calls can get so embedded the function calls becomes very difficult to follow.`(I can't understand the structure of this sentence enough)
* `Let's take another look at the code snippet above rewritten with the pipe operator.`

So I want a review.

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @hinamiyagk!  @3100 could you look at this when you have a moment? 😀

**Comment by 3100** [comment]
Sure.
I would translate themas follows: 

- 実際とても厄介なことに、関数呼び出しを深くしすぎると、把握するのがとても難しくなります。
- 先ほどのコードスニペットをパイプ演算子で書き直すとどうなるか、見てみましょう。

How do these look?

**Comment by hinamiyagk** [comment]
Thank you for your review!

**Comment by doomspork** [comment]
Teamwork ❤️

**Pull request merged**
