### PR TITLE
Change the Norwegian language code

### LINKED ISSUE #1090: Change the Norwegian language code
While trying to dig into pagination I ran into an issue with the Norwegian translation. Its language code is being interpreted as "false" according to the [yaml standard](http://yaml.org/type/bool.html).
There might be a plenty of workarounds but I thought that changing the language code might be the simplest one. The valid ISO 639 options are listed [here](https://en.m.wikipedia.org/wiki/List_of_ISO_639-1_codes) (`nb`, `nob`, `nor`, `nn`, `nno`).

I am ready to propose a PR once we come up with a decision.

RFC @doomspork @robinsjdotcom @Devalo.

### PR DESCRIPTION
**Pull request by nscyclone**
Closes #1090.
`no` is interpreted as `false` according to the [yaml standart](http://yaml.org/type/bool.html).

### CODE REVIEW

**Comment by doomspork** [comment]
I _think_ this may potentially generate a lot of dead links in Google.

**Comment by eksperimental** [comment]
@doomspork it can easily be solved with this plugin
https://github.com/jekyll/jekyll-redirect-from

**Comment by doomspork** [comment]
Sorry @nscyclone I haven't had a chance to look into the plugin @eksperimental shared I will do that this weekend 😁

**Comment by nscyclone** [comment]
I am a little confused. #1090 is now closed. But this PR had been updated yesterday to [address the `no` issue](https://github.com/doomspork/elixir-school/issues/1090#issuecomment-308159064), what is its fate now?

**Comment by doomspork** [comment]
@nscyclone I believe this PR can still be merged, @eksperimental do you foresee this impacting your other changes?

**Comment by eksperimental** [comment]
I would hold this for now until the other PR is reviewed.
The other PR is removing the need to define by langugage in the front-matter, It's automatically assumed based on the location of the file. So merging this won't be necessary,
plus I will have to rebase my PR.

**Comment by nscyclone** [comment]
Closed in favor of #1112.

**Pull request closed without merging**
