### PR TITLE
Basic support for German

### PR DESCRIPTION
**Pull request by Lechindianer**
Hey, 
as I already said on Twitter I started translating elixir-school into German :) Here are all basic tutorials and I already started to translate some of the advanced lessons. Expect to get another PR the next days when I'll translated the rest of it!

### CODE REVIEW

**Comment by ybur-yug** [comment]
Thank you a ton @Lechindianer! Since its the first translation, I imagine you've reviewed yourself quite thoroughly. In the future for new stuff it would be great to have someone else native/very fluent in the language review.

I'll merge this in. FOR REAL THOUGH, thanks, 2800 lines of translating is no small task :) <3

**Comment by doomspork** [comment]
Holy moly @Lechindianer, this is _awesome_!!  What was your twitter handle again?

**Comment by Lechindianer** [comment]
@doomspork same handle as here :)

@ybur-yug Most people here read programming books in English 'cause German translations of term from the computer domain may sound awful some times. I asked @TypedLambda and @blumenkraft to check out the new translation

**Comment by blumenkraft** [comment]
I do need to do some work in Git for Hacktoberfest, so this is very welcoming! :)

**Pull request merged**
