### PR TITLE
Add more language links to main page

### PR DESCRIPTION
**Pull request by brain-geek**

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @brain-geek!  This is something I've wanted to do for awhile. 👍

**Comment by Dalgona** [comment]
"Korean[ko]" should be translated into "한국어", not "우리말" :laughing:

**Comment by doomspork** [comment]
@Dalgona could you open a PR to correct it?  Thank you!

**Comment by Dalgona** [comment]
@doomspork Just opened it. Thanks!

**Comment by brain-geek** [comment]
@Dalgona Thanks for fixing this!

I've copied the name from wikipedia. :)

**Pull request merged**
