### PR TITLE
Make sidebar description translatable

### PR DESCRIPTION
**Pull request by brunoasantos**

### CODE REVIEW

**Comment by pragmaticivan** [comment]
Seems to be solid, including the message in Portuguese.
What do you think @doomspork ?

**Comment by pragmaticivan** [comment]
I also suggest updating the README and WIKI including this description option for new languages.

**Comment by doomspork** [comment]
This is great!  Thanks @brunoasantos!

ping @joneslee85, @jesusangelm, @cizixs in case you guys want to update translate the description after this merges.

**Comment by doomspork** [comment]
@pragmaticivan I agree about updating the WIKI.  I'd actually like to update the README to point to the WIKI for everything so it can be kept simple.

**Comment by doomspork** [comment]
@brunoasantos if you squash your typo commits I'd be glad to merge this.

**Comment by pragmaticivan** [comment]
@brunoasantos ping me on slack and I can help you with the squash.

**Comment by doomspork** [comment]
Thanks @pragmaticivan, I'm `seanc` on Slack btw.  Feel free to ping me whenever.

**Comment by brunoasantos** [comment]
@doomspork squashed. Sorry for that :)

**Comment by pragmaticivan** [comment]
By the way :+1: for the improvements in Portuguese. cc @doomspork you can merge.

**Comment by doomspork** [comment]
:boom:  Thanks so much @brunoasantos and @pragmaticivan for your review.

**Pull request merged**
