### PR TITLE
[KO] Update translation on exist documents

### PR DESCRIPTION
**Pull request by riseshia**
Changed:

- bump up version
- Use `Plug` instead of `플러그` via all translations

Remained work:

Totally not translated below.

- iex-helpers.md
- protocols.md
- debugging.md

I will translate these until next week... or is there someone to help?

@Dalgona, @malkoG, @devleoper, @marocchino  review please.

used diff: `git diff 65e4a61..dc9ab42 --word-diff -- lessons/`

related: #1043

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @riseshia! 😀

**Comment by marocchino** [comment]
👍LGTM

**Comment by marocchino** [comment]
& I can take one of them. Let us discuss later. @riseshia 😄

**Comment by riseshia** [comment]
@marocchino iex-helpers.md is already done yesterday XD #1070 so, just take one of the rest you want!

**Comment by marocchino** [comment]
@riseshia Then I will take debugging.

**Comment by riseshia** [comment]
@marocchino Thanks! XD

**Comment by riseshia** [comment]
ping @doomspork @devleoper

**Comment by doomspork** [comment]
You're on a roll @riseshia!  Thank you very much

**Pull request merged**
