### PR TITLE
[sk] Add Slovak translations of Basics lessons 12 and 13.

### PR DESCRIPTION
**Pull request by michalvalasek**

### CODE REVIEW

**Comment by doomspork** [comment]
:boom: 

This is awesome @michalvalasek!

**Comment by doomspork** [comment]
@michalvalasek I don't think we're currently tracking these lessons in a GitHub Issue, would that be helpful to you?  If so I'd be glad to get things setup.

**Comment by michalvalasek** [comment]
Hey @doomspork! I'm sorry but I don't think I understand the question. Why would we want to create an Issue for those lessons?

**Comment by doomspork** [comment]
Howdy @michalvalasek!  

Some of the other translators have found it's help to use an Issue to track the progress.  For example, here is the Russian Translation: https://github.com/doomspork/elixir-school/issues/220

It's up to you.  Thank you for your help 😀

**Comment by michalvalasek** [comment]
@doomspork Oh, thanks for explanation! It looks very cool but it probably wouldn't be that useful while I'm the only one working on SK translation. As soon as someone joins me I'll create such tracking issue. I really like it.

**Comment by doomspork** [comment]
Sounds good to me @michalvalasek, thanks again!

**Pull request merged**
