### PR TITLE
Translation of basic/01

### PR DESCRIPTION
**Pull request by Devalo**
Changed from "basis" to "grunnleggende" in config file,
fixed minor typo in frontpage index.md
translated basic 01 to norwegian

### CODE REVIEW

**Comment by doomspork** [comment]
@SirSJR would you mind looking at this translation since you know Norwegian? 😀

**Comment by doomspork** [comment]
@Devalo you're going to need to rebase base your branch, do you know how to do that?  If now, we can help you in Slack 😀

**Comment by doomspork** [comment]
That did the trick @Devalo 👍

**Comment by SirSJR** [comment]
@doomspork Read through it. It's well written. Ok to merge 👍  

Great job @Devalo 👍

**Pull request merged**
