### PR TITLE
Added iex output and fixed typos.

### PR DESCRIPTION
**Pull request by inchingforward**

### CODE REVIEW

**Comment by doomspork** [comment]
This looks good to me!  Thanks for the contribution @inchingforward :grinning:

**Comment by doomspork** [comment]
Actually @inchingforward before I merge, would you be open to making the `iex` output changes to the other languages?

**Comment by inchingforward** [comment]
Thanks for pointing that out.

**Comment by doomspork** [comment]
Thanks @inchingforward :+1:

**Pull request merged**
